### ISSUE TITLE
Is smart contract available on this gem?

### ISSUE THREAD

**Issue by NishidaRyu416** [44uk/nis-ruby#5]

**Comment by 44uk** [comment]
I don't know what you are saying "smart contract", but since _NEM_ does not have _a contract_ like _Ethereum_. So you need to implement it yourself.

**Comment by NishidaRyu416** [comment]
Mijin supports the function so can I use it on this gem?

**Comment by 44uk** [comment]
I think that you are talking about _aggregate transactions_. The detail have not been published. I will implement to support it when I get more information.

**Comment by NishidaRyu416** [comment]
Alright.
thank you for letting me know.
